project:
  type: website

website:
  title: "simple_quarto_website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.ipynb
    
      - href: slides/slides.ipynb
        text: Slides

format:
  html:
    theme:
      - cosmo
      - brand
    toc: true



